# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mavic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmavic.proto\x12\x05mavic\"\x07\n\x05\x45mpty\"I\n\tTelemetry\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0c\n\x04long\x18\x02 \x01(\x02\x12\x0f\n\x07heading\x18\x03 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x02\x32\x42\n\x10TelemetryService\x12.\n\x0cGetTelemetry\x12\x0c.mavic.Empty\x1a\x10.mavic.TelemetryB\x08\xaa\x02\x05mavicb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mavic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\005mavic'
  _EMPTY._serialized_start=22
  _EMPTY._serialized_end=29
  _TELEMETRY._serialized_start=31
  _TELEMETRY._serialized_end=104
  _TELEMETRYSERVICE._serialized_start=106
  _TELEMETRYSERVICE._serialized_end=172
# @@protoc_insertion_point(module_scope)
